sudo: false
language: node_js
node_js:
  - 8
  - 9
  - 10
  - stable

cache:
  bundle: true
  directories:
    - node_modules

jobs:
  include:
    - stage: Document deploy
      allow_failure: true
      script: npm run build:example
      node_js: stable
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: public

    - stage: Test
      script:
        - npm test -- --coverage
      after_script:
        - npm install codecov --no-save
        - codecov --token=$CODECOV_TOKEN
